### ISSUE TITLE
本機測試時 ?text 無法自動更改

### ISSUE THREAD

**Issue by pan93412** [EarlySpringCommitee/HowHow-web#3]
`window.history.pushState` ㄉ網址不用 `/?` ，只要 `?` ` 就好ㄌ。目前測試會：

```
Uncaught (in promise) DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///C:/?text=%E5%B9%B9' cannot be created in a document with origin 'null' and URL 'file:///C:/Users/pan93/HowHow-web/index.html'.
    at speak (file:///C:/Users/pan93/HowHow-web/assets/js/how-speak.js?6-2-1-36:58:20)
    at HTMLInputElement.<anonymous> (file:///C:/Users/pan93/HowHow-web/assets/js/how-speak.js?6-2-1-36:83:5)
    at HTMLInputElement.dispatch (file:///C:/Users/pan93/HowHow-web/assets/js/jquery.min.js:2:42571)
    at HTMLInputElement.v.handle (file:///C:/Users/pan93/HowHow-web/assets/js/jquery.min.js:2:40572)
```

**Comment by gnehs** [comment]
[![works badge](https://cdn.jsdelivr.net/gh/nikku/works-on-my-machine@v0.2.0/badge.svg)](https://github.com/nikku/works-on-my-machine)
我用 Prepros 沒遇過

**Comment by pan93412** [comment]
> [![works badge](https://camo.githubusercontent.com/0d6ff0ec2a11aea2bf004628f74f1c62c44ccbef/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6e696b6b752f776f726b732d6f6e2d6d792d6d616368696e654076302e322e302f62616467652e737667)](https://github.com/nikku/works-on-my-machine)
> 我用 Prepros 沒遇過

反正我都要改寫ㄌ 那就先扔著ㄅ
